Add driver home screen
avannus/JID-2327-RecycleMates pull request #30
Opened 2023-02-18 03:03 UTC by mayeverest

2023-02-18 04:58 UTC, avannus requested changes
Looks great, you're gonna have to teach me how you did all this :^)

2023-02-18 04:58 UTC, avannus commented on client/routes/index.js
> +      <Stack.Navigator initialRouteName='DriverHome'>
```suggestion
      <Stack.Navigator initialRouteName='Landing'>
```

2023-02-18 05:02 UTC, avannus approved these changes

2023-02-18 05:03 UTC, avannus approved these changes
Updated to reset the initial route back :)

2023-02-19 00:02 UTC, anaik62 approved these changes
looks good!

2023-02-19 00:16 UTC, jennyliu7 approved these changes
Looks good to me!

2023-02-19 00:19 UTC, merged